title: The SJG Garden
description: Mi viaje como diseñadora adentrándome en el mundo de la programación front-end
url: https://tunombredeusuario.github.io
baseurl: ""

# Tema (cambiamos de remote_theme a theme para probar)
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Configuración de navegación
header_pages:
  - proyectos.md
  - tutoriales.md
  - recursos.md
  - noticias.md

# Excluir archivos y carpetas
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
